version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "perf-testing-7"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1td7bs0l5853s"
s3_prefix = "perf-testing-7"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "website1=\"https://www.colypointobserver.com.au/\" website2=\"http://nvi.com.au/\""
