AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  performance-testing-tool

  Sample SAM Template for performance-testing-tool

Resources:
  PerformanceTestingStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/stock_trader.asl.json
      DefinitionSubstitutions:
        ScrapperFunctionArn: !GetAtt ScrapperFunction.Arn
        PerfTestingRunnerFunctionArn: !GetAtt PerfTestingRunnerFunction.Arn
      Events:
        PerformanceTestingSchedule:
          Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
          Properties:
            Description: Schedule to run the performance testing state machine every 15 sec
            Enabled: False # This schedule is disabled by default to avoid incurring charges.
            Schedule: "rate(1 hour)"
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref ScrapperFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref PerfTestingRunnerFunction

  ScrapperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/scrapper/
      Handler: app.lambda_handler
      Runtime: python3.8

  PerfTestingRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/perf_testing_runner/
      Handler: app.lambda_handler
      Runtime: python3.8


Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  PerformanceTestingStateMachineArn:
    Description: "Performance Testing State machine ARN"
    Value: !Ref PerformanceTestingStateMachine
  PerformanceTestingStateMachineRoleArn:
    Description: "IAM Role created for Stock Trading State machine based on the specified SAM Policy Templates"
    Value: !GetAtt PerformanceTestingStateMachineRole.Arn
